export const CURRENCY_MODE = "";
export const PERCENTAGE_MODE = "%";

// export const currencyList = [
//     "AED (د.إ)",
//     "AFN",
//     "ALL (Lek)",
//     "AMD",
//     "ANG (ƒ)",
//     "AOA (Kz)",
//     "ARS ($)",
//     "AUD ($)",
//     "AWG (ƒ)",
//     "AZN (ман)",
//     "BAM (KM)",
//     "BBD ($)",
//     "BDT (Tk)",
//     "BGN (лв)",
//     "BHD",
//     "BIF",
//     "BMD ($)",
//     "BND ($)",
//     "BOB ($b)",
//     "BOV",
//     "BRL (R$)",
//     "BSD ($)",
//     "BTN",
//     "BWP (P)",
//     "BYN (Br)",
//     "BZD (BZ$)",
//     "CAD ($)",
//     "CDF",
//     "CHE",
//     "CHF",
//     "CHW",
//     "CLF",
//     "CLP ($)",
//     "CNY (¥)",
//     "COP (p.)",
//     "COU",
//     "CRC (₡)",
//     "CUC",
//     "CUP (₱)",
//     "CVE",
//     "CZK (Kč)",
//     "DJF (CHF)",
//     "DKK (kr)",
//     "DOP (RD$)",
//     "DZD",
//     "EGP (E£)",
//     "ERN",
//     "ETB",
//     "EUR (€)",
//     "FJD ($)",
//     "FKP (£)",
//     "GBP (£)",
//     "GEL",
//     "GHS (GH¢)",
//     "GIP (£)",
//     "GMD",
//     "GNF",
//     "GTQ (Q)",
//     "GYD ($)",
//     "HKD (HK$)",
//     "HNL (L)",
//     "HTG",
//     "HUF (Ft)",
//     "IDR (Rp)",
//     "ILS (₪)",
//     "INR (Rs)",
//     "IQD",
//     "IRR",
//     "ISK (kr)",
//     "JMD (J$)",
//     "JOD",
//     "JPY (¥)",
//     "KES (KSh)",
//     "KGS (лв)",
//     "KHR (៛)",
//     "KMF",
//     "KPW (₩)",
//     "KRW (₩)",
//     "KWD (ك)",
//     "KYD ($)",
//     "KZT (лв)",
//     "LAK (₭)",
//     "LBP (£)",
//     "LKR (Rs)",
//     "LRD ($)",
//     "LSL",
//     "LYD (LD)",
//     "MAD",
//     "MDL",
//     "MGA",
//     "MKD (ден)",
//     "MMK",
//     "MNT (₮)",
//     "MOP",
//     "MRU",
//     "MUR (Rs)",
//     "MVR",
//     "MWK",
//     "MXN ($)",
//     "MXV",
//     "MYR (RM)",
//     "MZN (MT)",
//     "NAD (N$)",
//     "NGN (₦)",
//     "NIO (C$)",
//     "NOK (kr)",
//     "NPR (Rs)",
//     "NZD ($)",
//     "OMR",
//     "PAB (B/.)",
//     "PEN (S/.)",
//     "PGK",
//     "PHP (₱)",
//     "PKR (Rs)",
//     "PLN (zł)",
//     "PYG (Gs)",
//     "QAR",
//     "RON (lei)",
//     "RSD (Дин.)",
//     "RUB (руб)",
//     "RWF",
//     "SAR",
//     "SBD ($)",
//     "SCR (Rs)",
//     "SDG",
//     "SEK (kr)",
//     "SGD ($)",
//     "SHP (£)",
//     "SLE",
//     "SOS (S)",
//     "SRD ($)",
//     "SSP",
//     "STN",
//     "SVC ($)",
//     "SYP (£)",
//     "SZL",
//     "THB (฿)",
//     "TJS",
//     "TMT",
//     "TND (DT)",
//     "TOP",
//     "TRY",
//     "TTD (TT$)",
//     "TWD (NT$)",
//     "TZS (TSh)",
//     "UAH (₴)",
//     "UGX (USh)",
//     "USD ($)",
//     "USN",
//     "UYI",
//     "UYU ($U)",
//     "UYW",
//     "UZS (лв)",
//     "VED",
//     "VES",
//     "VND (₫)",
//     "VUV",
//     "WST",
//     "XAF",
//     "XAG",
//     "XAU",
//     "XBA",
//     "XBB",
//     "XBC",
//     "XBD",
//     "XCD ($)",
//     "XDR",
//     "XOF",
//     "XPD",
//     "XPF",
//     "XPT",
//     "XSU",
//     "XTS",
//     "XUA",
//     "XXX",
//     "YER",
//     "ZAR (R)",
//     "ZMW (ZK)",
//     "ZWL",
// ];

export const currencyList = [
    { id: "0AED", value: "AED", symbol: "AED", text: "AED - UAE Dirham (AED)" },
    { id: "1AFN", value: "AFN", symbol: "AFN", text: "AFN - Afghani (AFN)" },
    { id: "2ALL", value: "ALL", symbol: "Lek", text: "ALL - Lek (Lek)" },
    {
        id: "3AMD",
        value: "AMD",
        symbol: "AMD",
        text: "AMD - Armenian Dram (AMD)",
    },
    {
        id: "4ANG",
        value: "ANG",
        symbol: "ƒ",
        text: "ANG - Netherlands Antillian Guilder (ƒ)",
    },
    { id: "5AOA", value: "AOA", symbol: "AOA", text: "AOA - Kwanza (AOA)" },
    { id: "6ARS", value: "ARS", symbol: "$", text: "ARS - Argentine Peso ($)" },
    {
        id: "7AUD",
        value: "AUD",
        symbol: "$",
        text: "AUD - Australian Dollar ($)",
    },
    { id: "8AWG", value: "AWG", symbol: "ƒ", text: "AWG - Aruban Guilder (ƒ)" },
    {
        id: "9AZN",
        value: "AZN",
        symbol: "AZN",
        text: "AZN - Azerbaijanian Manat (AZN)",
    },
    {
        id: "10BAM",
        value: "BAM",
        symbol: "KM",
        text: "BAM - Convertible Marks (KM)",
    },
    { id: "11BBD", value: "BBD", symbol: "$", text: "BBD - Barbados Dollar ($)" },
    { id: "12BDT", value: "BDT", symbol: "BDT", text: "BDT - Taka (BDT)" },
    {
        id: "13BGN",
        value: "BGN",
        symbol: "BGN",
        text: "BGN - Bulgarian Lev (BGN)",
    },
    {
        id: "14BHD",
        value: "BHD",
        symbol: "BHD",
        text: "BHD - Bahraini Dinar (BHD)",
    },
    {
        id: "15BIF",
        value: "BIF",
        symbol: "BIF",
        text: "BIF - Burundi Franc (BIF)",
    },
    {
        id: "16BMD",
        value: "BMD",
        symbol: "$",
        text: "BMD - Bermudian Dollar (Bermuda Dollar) ($)",
    },
    { id: "17BND", value: "BND", symbol: "$", text: "BND - Brunei Dollar ($)" },
    { id: "18BOB", value: "BOB", symbol: "$b", text: "BOB - Boliviano ($b)" },
    { id: "19BOV", value: "BOV", symbol: "BOV", text: "BOV - Mvdol (BOV)" },
    {
        id: "20BRL",
        value: "BRL",
        symbol: "R$",
        text: "BRL - Brazilian Real (R$)",
    },
    { id: "21BSD", value: "BSD", symbol: "$", text: "BSD - Bahamian Dollar ($)" },
    { id: "22BTC", value: "BTC", symbol: "BTC", text: "BTC - Bitcoin (BTC)" },
    { id: "23BTN", value: "BTN", symbol: "BTN", text: "BTN - Ngultrum (BTN)" },
    { id: "24BWP", value: "BWP", symbol: "P", text: "BWP - Pula (P)" },
    {
        id: "25BYR",
        value: "BYR",
        symbol: "p.",
        text: "BYR - Belarussian Ruble (p.)",
    },
    {
        id: "26BZD",
        value: "BZD",
        symbol: "BZ$",
        text: "BZD - Belize Dollar (BZ$)",
    },
    { id: "27CAD", value: "CAD", symbol: "$", text: "CAD - Canadian Dollar ($)" },
    {
        id: "28CDF",
        value: "CDF",
        symbol: "CDF",
        text: "CDF - Franc Congolais (CDF)",
    },
    { id: "29CHE", value: "CHE", symbol: "CHE", text: "CHE - WIR Euro (CHE)" },
    { id: "30CHF", value: "CHF", symbol: "CHF", text: "CHF - Swiss Franc (CHF)" },
    { id: "31CHW", value: "CHW", symbol: "CHW", text: "CHW - WIR Franc (CHW)" },
    {
        id: "32CLF",
        value: "CLF",
        symbol: "CLF",
        text: "CLF - Unidades de formento (CLF)",
    },
    { id: "33CLP", value: "CLP", symbol: "$", text: "CLP - Chilean Peso ($)" },
    {
        id: "34CNY",
        value: "CNY",
        symbol: "CNY",
        text: "CNY - Yuan Renminbi (CNY)",
    },
    { id: "35COP", value: "COP", symbol: "$", text: "COP - Colombian Peso ($)" },
    {
        id: "36COU",
        value: "COU",
        symbol: "COU",
        text: "COU - Unidad de Valor Real (COU)",
    },
    {
        id: "37CRC",
        value: "CRC",
        symbol: "CRC",
        text: "CRC - Costa Rican Colon (CRC)",
    },
    {
        id: "38CUC",
        value: "CUC",
        symbol: "CUC$",
        text: "CUC - Cuba Convertible Peso (CUC$)",
    },
    { id: "39CUP", value: "CUP", symbol: "CUP", text: "CUP - Cuban Peso (CUP)" },
    {
        id: "40CVE",
        value: "CVE",
        symbol: "CVE",
        text: "CVE - Cape Verde Escudo (CVE)",
    },
    {
        id: "41CYP",
        value: "CYP",
        symbol: "CYP",
        text: "CYP - Cyprus Pound (CYP)",
    },
    {
        id: "42CZK",
        value: "CZK",
        symbol: "CZK",
        text: "CZK - Czech Koruna (CZK)",
    },
    {
        id: "43DJF",
        value: "DJF",
        symbol: "DJF",
        text: "DJF - Djibouti Franc (DJF)",
    },
    { id: "44DKK", value: "DKK", symbol: "kr", text: "DKK - Danish Krone (kr)" },
    {
        id: "45DOP",
        value: "DOP",
        symbol: "RD$",
        text: "DOP - Dominican Peso (RD$)",
    },
    {
        id: "46DZD",
        value: "DZD",
        symbol: "DZD",
        text: "DZD - Algerian Dinar (DZD)",
    },
    { id: "47EEK", value: "EEK", symbol: "kr", text: "EEK - Kroon (kr)" },
    { id: "48EGP", value: "EGP", symbol: "£", text: "EGP - Egyptian Pound (£)" },
    { id: "49ERN", value: "ERN", symbol: "ERN", text: "ERN - Nakfa (ERN)" },
    {
        id: "50ETB",
        value: "ETB",
        symbol: "ETB",
        text: "ETB - Ethiopian Birr (ETB)",
    },
    { id: "51EUR", value: "EUR", symbol: "€", text: "EUR - Euro (€)" },
    { id: "52FJD", value: "FJD", symbol: "$", text: "FJD - Fiji Dollar ($)" },
    {
        id: "53FKP",
        value: "FKP",
        symbol: "£",
        text: "FKP - Falkland Islands Pound (£)",
    },
    { id: "54GBP", value: "GBP", symbol: "£", text: "GBP - Pound Sterling (£)" },
    { id: "55GEL", value: "GEL", symbol: "GEL", text: "GEL - Lari (GEL)" },
    { id: "56GGP", value: "GGP", symbol: "£", text: "GGP - Guernsey Pound (£)" },
    { id: "57GHS", value: "GHS", symbol: "¢", text: "GHS - Cedi (¢)" },
    { id: "58GIP", value: "GIP", symbol: "£", text: "GIP - Gibraltar Pound (£)" },
    { id: "59GMD", value: "GMD", symbol: "GMD", text: "GMD - Dalasi (GMD)" },
    {
        id: "60GNF",
        value: "GNF",
        symbol: "GNF",
        text: "GNF - Guinea Franc (GNF)",
    },
    { id: "61GTQ", value: "GTQ", symbol: "Q", text: "GTQ - Quetzal (Q)" },
    {
        id: "62GWP",
        value: "GWP",
        symbol: "GWP",
        text: "GWP - Guinea-Bissau Peso (GWP)",
    },
    { id: "63GYD", value: "GYD", symbol: "$", text: "GYD - Guyana Dollar ($)" },
    {
        id: "64HKD",
        value: "HKD",
        symbol: "元",
        text: "HKD - Hong Kong Dollar (元)",
    },
    { id: "65HNL", value: "HNL", symbol: "L", text: "HNL - Lempira (L)" },
    { id: "66HRK", value: "HRK", symbol: "kn", text: "HRK - Croatian Kuna (kn)" },
    { id: "67HTG", value: "HTG", symbol: "HTG", text: "HTG - Gourde (HTG)" },
    { id: "68HUF", value: "HUF", symbol: "Ft", text: "HUF - Forint (Ft)" },
    { id: "69IDR", value: "IDR", symbol: "Rp", text: "IDR - Rupiah (Rp)" },
    {
        id: "70ILS",
        value: "ILS",
        symbol: "ILS",
        text: "ILS - New Israeli Sheqel (ILS)",
    },
    {
        id: "71IMP",
        value: "IMP",
        symbol: "£",
        text: "IMP - Isle of Man Pound (£)",
    },
    {
        id: "72INR",
        value: "INR",
        symbol: "Rs.",
        text: "INR - Indian Rupee (Rs.)",
    },
    { id: "73IQD", value: "IQD", symbol: "IQD", text: "IQD - Iraqi Dinar (IQD)" },
    {
        id: "74IRR",
        value: "IRR",
        symbol: "IRR",
        text: "IRR - Iranian Rial (IRR)",
    },
    { id: "75ISK", value: "ISK", symbol: "kr", text: "ISK - Iceland Krona (kr)" },
    { id: "76JEP", value: "JEP", symbol: "£", text: "JEP - Jersey Pound (£)" },
    {
        id: "77JMD",
        value: "JMD",
        symbol: "J$",
        text: "JMD - Jamaican Dollar (J$)",
    },
    {
        id: "78JOD",
        value: "JOD",
        symbol: "JOD",
        text: "JOD - Jordanian Dinar (JOD)",
    },
    { id: "79JPY", value: "JPY", symbol: "¥", text: "JPY - Yen (¥)" },
    {
        id: "80KES",
        value: "KES",
        symbol: "KES",
        text: "KES - Kenyan Shilling (KES)",
    },
    { id: "81KGS", value: "KGS", symbol: "KGS", text: "KGS - Som (KGS)" },
    { id: "82KHR", value: "KHR", symbol: "KHR", text: "KHR - Riel (KHR)" },
    {
        id: "83KMF",
        value: "KMF",
        symbol: "KMF",
        text: "KMF - Comoro Franc (KMF)",
    },
    {
        id: "84KPW",
        value: "KPW",
        symbol: "₩",
        text: "KPW - North Korean Won (₩)",
    },
    { id: "85KRW", value: "KRW", symbol: "₩", text: "KRW - Won (₩)" },
    {
        id: "86KWD",
        value: "KWD",
        symbol: "KWD",
        text: "KWD - Kuwaiti Dinar (KWD)",
    },
    {
        id: "87KYD",
        value: "KYD",
        symbol: "$",
        text: "KYD - Cayman Islands Dollar ($)",
    },
    { id: "88KZT", value: "KZT", symbol: "KZT", text: "KZT - Tenge (KZT)" },
    { id: "89LAK", value: "LAK", symbol: "LAK", text: "LAK - Kip (LAK)" },
    { id: "90LBP", value: "LBP", symbol: "£", text: "LBP - Lebanese Pound (£)" },
    {
        id: "91LKR",
        value: "LKR",
        symbol: "Rs",
        text: "LKR - Sri Lanka Rupee (Rs)",
    },
    { id: "92LRD", value: "LRD", symbol: "$", text: "LRD - Liberian Dollar ($)" },
    { id: "93LSL", value: "LSL", symbol: "LSL", text: "LSL - Loti (LSL)" },
    {
        id: "94LTL",
        value: "LTL",
        symbol: "Lt",
        text: "LTL - Lithuanian Litas (Lt)",
    },
    { id: "95LVL", value: "LVL", symbol: "Ls", text: "LVL - Latvian Lats (Ls)" },
    {
        id: "96LYD",
        value: "LYD",
        symbol: "LYD",
        text: "LYD - Libyan Dinar (LYD)",
    },
    {
        id: "97MAD",
        value: "MAD",
        symbol: "MAD",
        text: "MAD - Moroccan Dirham (MAD)",
    },
    {
        id: "98MDL",
        value: "MDL",
        symbol: "MDL",
        text: "MDL - Moldovan Leu (MDL)",
    },
    {
        id: "99MGA",
        value: "MGA",
        symbol: "MGA",
        text: "MGA - Malagascy Ariary (MGA)",
    },
    { id: "100MKD", value: "MKD", symbol: "MKD", text: "MKD - Denar (MKD)" },
    { id: "101MMK", value: "MMK", symbol: "MMK", text: "MMK - Kyat (MMK)" },
    { id: "102MNT", value: "MNT", symbol: "MNT", text: "MNT - Tugrik (MNT)" },
    { id: "103MOP", value: "MOP", symbol: "MOP", text: "MOP - Pataca (MOP)" },
    { id: "104MRO", value: "MRO", symbol: "MRO", text: "MRO - Ouguiya (MRO)" },
    {
        id: "105MTL",
        value: "MTL",
        symbol: "MTL",
        text: "MTL - Maltese Lira (MTL)",
    },
    {
        id: "106MUR",
        value: "MUR",
        symbol: "Rp",
        text: "MUR - Mauritius Rupee (Rp)",
    },
    { id: "107MVR", value: "MVR", symbol: "MVR", text: "MVR - Rufiyaa (MVR)" },
    { id: "108MWK", value: "MWK", symbol: "MWK", text: "MWK - Kwacha (MWK)" },
    { id: "109MXN", value: "MXN", symbol: "$", text: "MXN - Mexican Peso ($)" },
    {
        id: "110MXV",
        value: "MXV",
        symbol: "MXV",
        text: "MXV - Mexican Unidad de Inversion (UID) (MXV)",
    },
    {
        id: "111MYR",
        value: "MYR",
        symbol: "RM",
        text: "MYR - Malaysian Ringgit (RM)",
    },
    { id: "112MZN", value: "MZN", symbol: "MT", text: "MZN - Metical (MT)" },
    {
        id: "113NAD",
        value: "NAD",
        symbol: "$",
        text: "NAD - Namibian Dollar ($)",
    },
    { id: "114NGN", value: "NGN", symbol: "NGN", text: "NGN - Naira (NGN)" },
    { id: "115NIO", value: "NIO", symbol: "C$", text: "NIO - Cordoba Oro (C$)" },
    {
        id: "116NOK",
        value: "NOK",
        symbol: "kr",
        text: "NOK - Norwegian Krone (kr)",
    },
    {
        id: "117NPR",
        value: "NPR",
        symbol: "Rp",
        text: "NPR - Nepalese Rupee (Rp)",
    },
    {
        id: "118NZD",
        value: "NZD",
        symbol: "$",
        text: "NZD - New Zealand Dollar ($)",
    },
    { id: "119OMR", value: "OMR", symbol: "OMR", text: "OMR - Rial Omani (OMR)" },
    { id: "120PAB", value: "PAB", symbol: "B/.", text: "PAB - Balboa (B/.)" },
    { id: "121PEN", value: "PEN", symbol: "S/.", text: "PEN - Nuevo Sol (S/.)" },
    { id: "122PGK", value: "PGK", symbol: "PGK", text: "PGK - Kina (PGK)" },
    {
        id: "123PHP",
        value: "PHP",
        symbol: "Php",
        text: "PHP - Philippine Peso (Php)",
    },
    {
        id: "124PKR",
        value: "PKR",
        symbol: "Rs",
        text: "PKR - Pakistan Rupee (Rs)",
    },
    { id: "125PLN", value: "PLN", symbol: "PLN", text: "PLN - Zloty (PLN)" },
    { id: "126PYG", value: "PYG", symbol: "Gs", text: "PYG - Guarani (Gs)" },
    {
        id: "127QAR",
        value: "QAR",
        symbol: "QAR",
        text: "QAR - Qatari Rial (QAR)",
    },
    { id: "128ROL", value: "ROL", symbol: "ROL", text: "ROL - Old Leu (ROL)" },
    { id: "129RON", value: "RON", symbol: "lei", text: "RON - New Leu (lei)" },
    {
        id: "130RSD",
        value: "RSD",
        symbol: "RSD",
        text: "RSD - Serbian Dinar (RSD)",
    },
    {
        id: "131RUB",
        value: "RUB",
        symbol: "RUB",
        text: "RUB - Russian Ruble (RUB)",
    },
    {
        id: "132RWF",
        value: "RWF",
        symbol: "RWF",
        text: "RWF - Rwanda Franc (RWF)",
    },
    {
        id: "133SAR",
        value: "SAR",
        symbol: "SAR",
        text: "SAR - Saudi Riyal (SAR)",
    },
    {
        id: "134SBD",
        value: "SBD",
        symbol: "$",
        text: "SBD - Solomon Islands Dollar ($)",
    },
    {
        id: "135SCR",
        value: "SCR",
        symbol: "Rp",
        text: "SCR - Seychelles Rupee (Rp)",
    },
    {
        id: "136SDD",
        value: "SDD",
        symbol: "SDD",
        text: "SDD - Sudanese Dinar (SDD)",
    },
    {
        id: "137SDG",
        value: "SDG",
        symbol: "SDG",
        text: "SDG - Sudanese Pound (SDG)",
    },
    {
        id: "138SEK",
        value: "SEK",
        symbol: "kr",
        text: "SEK - Swedish Krona (kr)",
    },
    {
        id: "139SGD",
        value: "SGD",
        symbol: "$",
        text: "SGD - Singapore Dollar ($)",
    },
    {
        id: "140SHP",
        value: "SHP",
        symbol: "£",
        text: "SHP - Saint Helena Pound (£)",
    },
    { id: "141SIT", value: "SIT", symbol: "SIT", text: "SIT - Tolar (SIT)" },
    {
        id: "142SKK",
        value: "SKK",
        symbol: "SKK",
        text: "SKK - Slovak Koruna (SKK)",
    },
    { id: "143SLL", value: "SLL", symbol: "SLL", text: "SLL - Leone (SLL)" },
    {
        id: "144SOS",
        value: "SOS",
        symbol: "S",
        text: "SOS - Somali Shilling (S)",
    },
    { id: "145SRD", value: "SRD", symbol: "$", text: "SRD - Surinam Dollar ($)" },
    { id: "146STD", value: "STD", symbol: "STD", text: "STD - Dobra (STD)" },
    {
        id: "147SVC",
        value: "SVC",
        symbol: "$",
        text: "SVC - El Salvador Colon ($)",
    },
    { id: "148SYP", value: "SYP", symbol: "£", text: "SYP - Syrian Pound (£)" },
    { id: "149SZL", value: "SZL", symbol: "SZL", text: "SZL - Lilangeni (SZL)" },
    { id: "150THB", value: "THB", symbol: "THB", text: "THB - Baht (THB)" },
    { id: "151TJS", value: "TJS", symbol: "TJS", text: "TJS - Somoni (TJS)" },
    { id: "152TMT", value: "TMT", symbol: "TMT", text: "TMT - Manat (TMT)" },
    {
        id: "153TND",
        value: "TND",
        symbol: "TND",
        text: "TND - Tunisian Dinar (TND)",
    },
    { id: "154TOP", value: "TOP", symbol: "TOP", text: "TOP - Paanga (TOP)" },
    { id: "155TRL", value: "TRL", symbol: "TL", text: "TRL - Turkish Lira (TL)" },
    {
        id: "156TRY",
        value: "TRY",
        symbol: "YTL",
        text: "TRY - New Turkish Lira (YTL)",
    },
    {
        id: "157TTD",
        value: "TTD",
        symbol: "TT$",
        text: "TTD - Trinidad and Tobago Dollar (TT$)",
    },
    { id: "158TVD", value: "TVD", symbol: "$", text: "TVD - Tuvalu Dollar ($)" },
    {
        id: "159TWD",
        value: "TWD",
        symbol: "NT$",
        text: "TWD - New Taiwan Dollar (NT$)",
    },
    {
        id: "160TZS",
        value: "TZS",
        symbol: "TZS",
        text: "TZS - Tanzanian Shilling (TZS)",
    },
    { id: "161UAH", value: "UAH", symbol: "UAH", text: "UAH - Hryvnia (UAH)" },
    {
        id: "162UGX",
        value: "UGX",
        symbol: "UGX",
        text: "UGX - Uganda Shilling (UGX)",
    },
    { id: "163USD", value: "USD", symbol: "$", text: "USD - US Dollar ($)" },
    {
        id: "164UYI",
        value: "UYI",
        symbol: "UYI",
        text: "UYI - Uruguay Peso en Unidades Indexadas (UYI)",
    },
    {
        id: "165UYU",
        value: "UYU",
        symbol: "$U",
        text: "UYU - Peso Uruguayo ($U)",
    },
    {
        id: "166UZS",
        value: "UZS",
        symbol: "UZS",
        text: "UZS - Uzbekistan Sum (UZS)",
    },
    { id: "167VEB", value: "VEB", symbol: "VEB", text: "VEB - Bolivar (VEB)" },
    {
        id: "168VEF",
        value: "VEF",
        symbol: "VEF",
        text: "VEF - Bolivar Fuerte (VEF)",
    },
    { id: "169VND", value: "VND", symbol: "VND", text: "VND - Dong (VND)" },
    { id: "170VUV", value: "VUV", symbol: "VUV", text: "VUV - Vatu (VUV)" },
    { id: "171WST", value: "WST", symbol: "WST", text: "WST - Tala (WST)" },
    {
        id: "172XAF",
        value: "XAF",
        symbol: "XAF",
        text: "XAF - CFA Franc BEAC (XAF)",
    },
    {
        id: "173XCD",
        value: "XCD",
        symbol: "$",
        text: "XCD - East Caribbean Dollar ($)",
    },
    { id: "174XDR", value: "XDR", symbol: "XDR", text: "XDR - SDR (XDR)" },
    {
        id: "175XOF",
        value: "XOF",
        symbol: "XOF",
        text: "XOF - CFA Franc BCEAO (XOF)",
    },
    { id: "176XPF", value: "XPF", symbol: "XPF", text: "XPF - CFP Franc (XPF)" },
    {
        id: "177YER",
        value: "YER",
        symbol: "YER",
        text: "YER - Yemeni Rial (YER)",
    },
    { id: "178ZAR", value: "ZAR", symbol: "R", text: "ZAR - Rand (R)" },
    { id: "179ZMK", value: "ZMK", symbol: "ZMK", text: "ZMK - Kwacha (ZMK)" },
    {
        id: "180ZWD",
        value: "ZWD",
        symbol: "Z$",
        text: "ZWD - Zimbabwe Dollar (Z$)",
    },
];
